language: c

compiler:
    - gcc
    - clang

addons:
    apt:
        packages:
            - automake
            - autoconf
            - gdb
            - libtool
            - autotools-dev
            - valgrind

matrix:
    exclude:
        - compiler: "gcc"
        - compiler: "clang"
    include:
        - compiler: "gcc"
          env: SERV="mariadb", VERSION="5.5", CFLAGS="-g -O2 -Wall"
          dist: trusty
#        - compiler: "clang"
#          env: SERV="mariadb", VERSION="5.5", CFLAGS="-g -O2 -Wall"
#          dist: trusty

before_install:
    - sudo /bin/bash travis/trusty-${SERV}.sh ${VERSION}

script:
    - mysql_config --plugindir && echo -n "Current directory: " && pwd
    #    - ./configure && make && sudo make install && /bin/bash travis/test.sh

notifications:
      email: false
