language: c

compiler:
    - gcc

addons:
    apt:
        packages:
            - automake
            - autoconf
            - libtool
            - autotools-dev

matrix:
    exclude:
        - compiler: "gcc"
    include:
        - compiler: "gcc"
          env: SERV="mariadb", VERSION="10.0", CFLAGS="-g -O2 -Wall"
          dist: trusty

before_install:
    - sudo /bin/bash travis/trusty-${SERV}.sh ${VERSION}

script:
    ./configure --with-mysql-plugins-dir=/usr/lib/mysql/plugin && make && sudo make install && sudo /bin/bash travis/test.sh

notifications:
      email: false
